import 'package:ctfl_vertragsmanager/models/labels.dart';
import 'package:flutter/material.dart';
import 'vertrag.dart';

class Vertragsdaten {
  final _vertraege = [
    Vertrag(
      name: "Netflix",
      description: "Beschreibung",
      beitrag: 12.99,
      erstZahlung: DateTime(2020, 12, 2),
      naechsteZahlung: DateTime(2020, 12, 2),
      label: Labels.getLabel(0),
      intervall: Intervall.monatlich,
      kuendigungsfrist: DateTime(2020, 12, 2),
      vertragsBeginn: DateTime(2020, 12, 2),
      vertragsEnde: DateTime(2020, 12, 2),
      vertragspartner: 'Netflix',
    ),
    Vertrag(
      name: "Spotify",
      description: "Beschreibung",
      beitrag: 9.99,
      erstZahlung: DateTime(2020, 12, 2),
      naechsteZahlung: DateTime(2020, 12, 2),
      label: Labels.getLabel(1),
      intervall: Intervall.monatlich,
      kuendigungsfrist: DateTime(2020, 12, 2),
      vertragsBeginn: DateTime(2020, 12, 2),
      vertragsEnde: DateTime(2020, 12, 2),
      vertragspartner: 'Spotify',
    ),
    Vertrag(
      name: "Kfz-Haftpflicht",
      description: "Beschreibung",
      beitrag: 30.99,
      erstZahlung: DateTime(2020, 12, 2),
      naechsteZahlung: DateTime(2020, 12, 2),
      label: Labels.getLabel(2),
      intervall: Intervall.monatlich,
      kuendigungsfrist: DateTime(2020, 12, 2),
      vertragsBeginn: DateTime(2020, 12, 2),
      vertragsEnde: DateTime(2020, 12, 2),
      vertragspartner: 'SV SparkassenVersicherung',
    ),
    Vertrag(
      name: "Vollkasko",
      description: "Beschreibung",
      beitrag: 25.99,
      erstZahlung: DateTime(2020, 12, 2),
      naechsteZahlung: DateTime(2020, 12, 2),
      label: Labels.getLabel(2),
      intervall: Intervall.monatlich,
      kuendigungsfrist: DateTime(2020, 12, 2),
      vertragsBeginn: DateTime(2020, 12, 2),
      vertragsEnde: DateTime(2020, 12, 2),
      vertragspartner: 'SV SparkassenVersicherung',
    ),
    Vertrag(
      name: "Hausrat",
      description: "Beschreibung",
      beitrag: 17.99,
      erstZahlung: DateTime(2020, 12, 2),
      naechsteZahlung: DateTime(2020, 12, 2),
      label: Labels.getLabel(3),
      intervall: Intervall.monatlich,
      kuendigungsfrist: DateTime(2020, 12, 2),
      vertragsBeginn: DateTime(2020, 12, 2),
      vertragsEnde: DateTime(2020, 12, 2),
      vertragspartner: 'SV SparkassenVersicherung',
    ),
    Vertrag(
      name: "Berufsunfähigkeit",
      description: "Beschreibung",
      beitrag: 40.99,
      erstZahlung: DateTime(2020, 12, 2),
      naechsteZahlung: DateTime(2020, 12, 2),
      label: Labels.getLabel(4),
      intervall: Intervall.monatlich,
      kuendigungsfrist: DateTime(2020, 12, 2),
      vertragsBeginn: DateTime(2020, 12, 2),
      vertragsEnde: DateTime(2020, 12, 2),
      vertragspartner: 'SV SparkassenVersicherung',
    ),
    Vertrag(
      name: "Netflix",
      label: Labels.getLabel(0),
      description: "Beispiel",
      vertragspartner: "Netflix",
      vertragsBeginn: DateTime(2022, 01, 01),
      vertragsEnde: DateTime(2023, 01, 01),
      kuendigungsfrist: DateTime(2022, 12, 01),
      intervall: Intervall.quartal,
      beitrag: 12.50,
      erstZahlung: DateTime(2022, 12, 01),
      naechsteZahlung: DateTime(2022, 12, 01),
    ),
    Vertrag(
      name: "Netflix",
      label: Labels.getLabel(0),
      description: "Beispiel",
      vertragspartner: "Netflix",
      vertragsBeginn: DateTime(2022, 01, 01),
      vertragsEnde: DateTime(2023, 01, 01),
      kuendigungsfrist: DateTime(2022, 12, 01),
      intervall: Intervall.quartal,
      beitrag: 12.50,
      erstZahlung: DateTime(2022, 12, 01),
      naechsteZahlung: DateTime(2022, 12, 01),
    ),
    Vertrag(
      name: "Netflix",
      label: Labels.getLabel(0),
      description: "Beispiel",
      vertragspartner: "Netflix",
      vertragsBeginn: DateTime(2022, 01, 01),
      vertragsEnde: DateTime(2023, 01, 01),
      kuendigungsfrist: DateTime(2022, 12, 01),
      intervall: Intervall.quartal,
      beitrag: 12.50,
      erstZahlung: DateTime(2022, 12, 01),
      naechsteZahlung: DateTime(2022, 12, 01),
    ),
  ];

  List<Vertrag> get vertraege {
    return _vertraege;
  }
}
